  AOD:
  BTR:
  CAL:
  CFC:
    CFCmm002AVPOS01:
      Dataset: CLARA-2, AVHRR on polar orbiting satellites
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm221AVPOS01:
      Dataset: CLARA-2, AVHRR on polar orbiting satellites
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
        polar: TRUE
    CFCmm219AVPOS01:
      Dataset: CLARA-2, AVHRR on polar orbiting satellites
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm400AVPOS01:
      Dataset: ICDR AVHRR
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm410SVMSG01:
      Dataset: ICDR Seviri Clouds
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmd410SVMSG01:
      Dataset: ICDR Seviri Clouds
      CFC_MMDC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm410SVMSG01:
      Dataset: ICDR Seviri Clouds
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm400AVPOS01:
      Dataset: ICDR AVHRR
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmd0011000101:
      Dataset: CM SAF COMET
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm0011000101:
      Dataset: CM SAF COMET
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm0011000101:
      Dataset: CM SAF COMET
      CFC_MMDC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN0701:
      Dataset: CLARA-A2, AVHRR on NOAA-07
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN0701:
      Dataset: CLARA-A2, AVHRR on NOAA-07
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN0901:
      Dataset: CLARA-A2, AVHRR on NOAA-09
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN0901:
      Dataset: CLARA-A2, AVHRR on NOAA-09
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1101:
      Dataset: CLARA-A2, AVHRR on NOAA-11
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1101:
      Dataset: CLARA-A2, AVHRR on NOAA-11
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1201:
      Dataset: CLARA-A2, AVHRR on NOAA-12
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1201:
      Dataset: CLARA-A2, AVHRR on NOAA-12
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1401:
      Dataset: CLARA-A2, AVHRR on NOAA-14
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1401:
      Dataset: CLARA-A2, AVHRR on NOAA-14
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1501:
      Dataset: CLARA-A2, AVHRR on NOAA-15
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1501:
      Dataset: CLARA-A2, AVHRR on NOAA-15
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1601:
      Dataset: CLARA-A2, AVHRR on NOAA-16
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1601:
      Dataset: CLARA-A2, AVHRR on NOAA-16
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1701:
      Dataset: CLARA-A2, AVHRR on NOAA-17
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1701:
      Dataset: CLARA-A2, AVHRR on NOAA-17
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1801:
      Dataset: CLARA-A2, AVHRR on NOAA-18
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1801:
      Dataset: CLARA-A2, AVHRR on NOAA-18
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVN1901:
      Dataset: CLARA-A2, AVHRR on NOAA-19
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVN1901:
      Dataset: CLARA-A2, AVHRR on NOAA-19
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVMEA01:
      Dataset: CLARA-A2, AVHRR on METOP-A
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVMEA01:
      Dataset: CLARA-A2, AVHRR on METOP-A
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVMEB01:
      Dataset: CLARA-A2, AVHRR on METOP-B
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVMEB01:
      Dataset: CLARA-A2, AVHRR on METOP-B
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color    
    CFCmm0010016001:
      Dataset: CLAAS-1
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm0010016001:
      Dataset: CLAAS-1
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm003SVMSG01:
      Dataset: CLAAS-2
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm003SVMSG01:
      Dataset: CLAAS-2
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCmm002AVPOSE1:
      Dataset: CLARA-A2.1, AVHRR on polar orbiting satellites
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CFCdm002AVPOSE1:
      Dataset: CLARA-A2.1, AVHRR on polar orbiting satellites
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
  CFL:
  CFS:
  CMA:
    CMAin003SVMSG01:
      Dataset: CLAAS-2
      CMA:
        limits:
          min: 0
          max: 3
        legend: FALSE
        colorscale: clouds
        logo: color
    CMAin003SVMSGE1:
      Dataset: CLAAS-2
      CMA:
        limits:
          min: 0
          max: 3
        legend: FALSE
        colorscale: clouds
        logo: color
  COT:
  CPH:
    CPHmm400AVPOS01:
      Dataset: ICDR AVHRR
      CPH:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
    CPHdm400AVPOS01:
      Dataset: ICDR AVHRR
      CPH:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
  CPP:
# CTH:
  CTO:
    CTOdm003SVMSG01:
      Dataset: CLAAS-2.1
      CTT:
        limits:
          min: 150
          max: 340
        legend: TRUE
        colorscale: PinkYl
        logo: color
      CTH:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: Greens
        logo: color
        invert_col: TRUE
      CTP:
        limits:
          min: 100
          max: 1000
        legend: TRUE
        colorscale: Purples
        logo: color 
    CTOdm410SVMSG01:
      Dataset: ICDR Seviri Clouds
      CTT:
        limits:
          min: 190
          max: 300
        legend: TRUE
        colorscale: terrain.colors
        logo: color
      CTH:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        invert_col: TRUE
      CTP:
        limits:
          min: 100
          max: 1000
        legend: TRUE
        colorscale: terrain.colors
        logo: color 
    CTOdm400AVPOS01:
      Dataset: ICDR AVHRR
      CTT:
        limits:
          min: 190
          max: 300
        legend: TRUE
        colorscale: terrain.colors
        logo: color
      CTH:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        invert_col: TRUE
      CTP:
        limits:
          min: 100
          max: 1000
        legend: TRUE
        colorscale: terrain.colors
        logo: color
    CTOmd410SVMSG01:
      Dataset: ICDR Seviri Clouds
      CTT_MMDC:
        limits:
          min: 190
          max: 300
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        slot: 13
      CTH_MMDC:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        slot: 13
        invert_col: TRUE
      CTP_MMDC:
        limits:
          min: 100
          max: 1000
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        slot: 13
    CTOmm410SVMSG01:
      Dataset: ICDR Seviri Clouds
      CTT:
        limits:
          min: 190
          max: 300
        legend: TRUE
        colorscale: terrain.colors
        logo: color
      CTH:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        invert_col: TRUE
      CTP:
        limits:
          min: 100
          max: 1000
        legend: TRUE
        colorscale: terrain.colors
        logo: color
    CTOmm400AVPOS01:
      Dataset: ICDR AVHRR
      CTT:
        limits:
          min: 190
          max: 300
        legend: TRUE
        colorscale: terrain.colors
        logo: color
      CTH:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: terrain.colors
        logo: color
        invert_col: TRUE
      CTP:
        limits:
          min: 100
          max: 1000
        legend: TRUE
        colorscale: terrain.colors
        logo: color
# CTP:      
# CTT:
  CTX:
    CTXin003SVMSGE1:
      Dataset: CLAAS-2
      CTP:
        limits:
          min: 500
          max: 10000
        legend: TRUE
        colorscale: Purples
        logo: color
      CTT:
        limits:
          min: 150
          max: 340
        legend: TRUE
        colorscale: PinkYl
        logo: color
      CTH:
        limits:
          min: 1
          max: 18600
        legend: TRUE
        colorscale: Greens
        logo: color
# CTY:
  CWP:
  DAL:
  DNI:
    DNIdm4101000101:
      Dataset: ICDR Seviri Radiation
      DNI:
        limits:
          min: 0
          max: 750
        legend: TRUE
        colorscale: YlOrRd
        logo: color
    DNIin4101000101:
      Dataset: ICDR Seviri Radiation
      DNI:
        limits:
          min: 0
          max: 1200
        legend: TRUE
        colorscale: YlOrRd
        logo: color
        slot: 25
    DNImm4101000101:
      Dataset: ICDR Seviri Radiation
      DNI:
        limits:
          min: 0
          max: 500
        legend: TRUE
        colorscale: YlOrRd
        logo: color
  EMP:
    EMPmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      BUDG:
        limits:
          min: -7
          max: 7
        legend: TRUE
        colorscale: Blue-Red 3
        logo: color
  EVA:
    EVAmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      EVAP:
        limits:
          min: 0
          max: 17.5
        legend: TRUE
        colorscale: Blues 3
        logo: color
  FTH:
    FTHmm0010044801:
      Dataset: CM SAF FTH
      FTH:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues 3
        logo: color
  HLW:
  HSH:
  HTW:
    HTWmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      WVPA:
        limits:
          min: 0
          max: 70
        legend: TRUE
        colorscale: Blues
        logo: color
  IWP:
    IWPmm400AVPOS01:
      Dataset: ICDR AVHRR
      IWP:
        limits:
          min: 0
          max: 0.4
        legend: TRUE
        colorscale: Plasma
        logo: color
    IWPdm400AVPOS01:
      Dataset: ICDR AVHRR
      IWP:
        limits:
          min: 0
          max: 0.5
        legend: TRUE
        colorscale: Plasma
        logo: color
  JCH:
    JCHmh002AVPOS01:
      Dataset: CLARA-A2.1, AVHRR on polar orbiting satellites
      CFC:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
  LHF:
    LHFmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      LATE:
        limits:
          min: 0
          max: 350
        legend: TRUE
        colorscale: Blues 
        logo: color
  LTP:
  LTS:
  LWP:
    LWPmm400AVPOS01:
      Dataset: ICDR AVHRR
      LWP:
        limits:
          min: 0
          max: 0.4
        legend: TRUE
        colorscale: Plasma
        logo: color
    LWPdm400AVPOS01:
      Dataset: ICDR AVHRR
      LWP:
        limits:
          min: 0
          max: 0.5
        legend: TRUE
        colorscale: Plasma
        logo: color
    LWPmm002AVPOS01:
      Dataset: CLARA-A2, AVHRR on polar orbiting satellites
      LWP:
        limits:
          min: 0
          max: 0.4
        legend: TRUE
        colorscale: Plasma
        logo: color
    LWPdm002AVPOS01:
      Dataset: CLARA-A2, AVHRR on polar orbiting satellites
      LWP:
        limits:
          min: 0
          max: 0.5
        legend: TRUE
        colorscale: Plasma
        logo: color
  NSH:
    NSHmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      HAIR:
        limits:
          min: 0
          max: 25
        legend: TRUE
        colorscale: Blues
        logo: color
    
  PRE:
    PREmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      RAIN:
        limits:
          min: 0
          max: 60
        legend: TRUE
        colorscale: Oslo
        logo: color
  SAL:
    SALmm400AVPOS01:
      Dataset: ICDR AVHRR
      SAL:
        limits:
          min: 0
          max: 120
        legend: TRUE
        colorscale: topo.colors
        logo: color
    SALpm400AVPOS01:
      Dataset: ICDR AVHRR
      SAL:
        limits:
          min: 0
          max: 120
        legend: TRUE
        colorscale: topo.colors
        logo: color
  SDL:
  SDU:
    SDUds4001000101:
      Dataset: SARAH-2.0
      SDU:
        limits:
          min: 0
          max: 20
        legend: TRUE
        colorscale: Plasma
        logo: color
    SDUds4011000101:
      Dataset: ICDR Seviri Radiation
      SDU:
        limits:
          min: 0
          max: 20
        legend: TRUE
        colorscale: Plasma
        logo: color
    SDUms4011000101:
      Dataset: ICDR Seviri Radiation
      SDU:
        limits:
          min: 0
          max: 400
        legend: TRUE
        colorscale: Plasma
        logo: color
  SID:
    SIDdm4101000101:
      Dataset: ICDR Seviri Radiation
      SID:
        limits:
          min: 0
          max: 450
        legend: TRUE
        colorscale: YlOrRd
        logo: color
    SIDin4101000101:
      Dataset: ICDR Seviri Radiation
      SID:
        limits:
          min: 0
          max: 1200
        legend: TRUE
        colorscale: YlOrRd
        logo: color
        slot: 25
    SIDmm4101000101:
      Dataset: ICDR Seviri Radiation
      SID:
        limits:
          min: 0
          max: 450
        legend: TRUE
        colorscale: YlOrRd
        logo: color
  SIS:
    SISdm4101000101:
      Dataset: ICDR Seviri Radiation
      SIS:
        limits:
          min: 0
          max: 450
        legend: TRUE
        colorscale: Viridis
        logo: color
    SISin4101000101:
      Dataset: ICDR Seviri Radiation
      SIS:
        limits:
          min: 0
          max: 1200
        legend: TRUE
        colorscale: Viridis
        logo: color
        slot: 25
    SISmm4101000101:
      Dataset: ICDR Seviri Radiation
      SIS:
        limits:
          min: 0
          max: 450
        legend: TRUE
        colorscale: Viridis
        logo: color
    SISmm400AVPOS01:
      Dataset: ICDR AVHRR
      SIS:
        limits:
          min: 0
          max: 450
        legend: TRUE
        colorscale: Viridis
        logo: color
    SISdm400AVPOS01:
      Dataset: ICDR AVHRR
      SIS:
        limits:
          min: 0
          max: 450
        legend: TRUE
        colorscale: Viridis
        logo: color
  SNL:
  SNS:
  SOL:
    SOLmm002AVPOS01:
      Dataset: CLARA-A2, AVHRR on polar orbiting satellites
      SOL:
        limits:
          min: 0
          max: 700
        legend: TRUE
        colorscale: Viridis
        logo: color
    SOLdm002AVPOS01:
      Dataset: CLARA-A2, AVHRR on polar orbiting satellites
      SOL:
        limits:
          min: 0
          max: 800
        legend: TRUE
        colorscale: Viridis
        logo: color
  SRB:
  SRI:
  SWS:
    SWSmm002SCPOS01:
      Dataset: HOAPS, version 4.0
      WIND:
        limits:
          min: 0
          max: 17.5
        legend: TRUE
        colorscale: Blue-Red
        logo: color
  TET:
  TIS:
  TRS:
  UTH:
    UTHdm001MHMEB01:
      Dataset: CM SAF UTH
      UTH_MEAN_ASCEND:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
      UTH_MEAN_ASCEND_DESCEND:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
      UTH_MEAN_DESCEND:
        limits:
          min: 0
          max: 100
        legend: TRUE
        colorscale: Blues
        logo: color
